language: python
python:
    - "2.6"
    - "2.7"
# command to install dependencies
install:
    - pip install flake8
    - python setup.py install
# command to run before scripts
before_script:
    - flake8 --max-complexity=10 --statistics --benchmark .
# command to run tests
script: nosetests
